Sistema Ventas: process_upload_img.php File Reference
process_upload_img.php File Reference
Functions
if(isset($_POST) &&isset($_SERVER[ 'HTTP_X_REQUESTED_WITH']) &&strtolower($_SERVER[ 'HTTP_X_REQUESTED_WITH'])=='xmlhttprequest') normal_resize_image ($source, $destination, $image_type, $max_size, $image_width, $image_height, $quality)
crop_image_square ($source, $destination, $image_type, $square_size, $image_width, $image_height, $quality)
save_image ($source, $destination, $image_type, $quality)
Variables
$arryv = explode("*", $_POST['txtidf'])
$vidv = $arryv[0]
$minv = $arryv[1]
$maxv = $arryv[2]
$usnnv = $arryv[3]
$rimgv = $arryv[4]
$usnmv = $arryv[5]
$thumb_square_size = $minv
$max_image_size = $maxv
$thumb_prefix = "ch_"
$destination_folder = $rimgv
$jpeg_quality = 90
Function Documentation
crop_image_square()
crop_image_square ($source, $destination, $image_type, $square_size, $image_width, $image_height, $quality)
{
    if($image_width <= 0 || $image_height <= 0){return false;} //return false if nothing to resize
    if( $image_width > $image_height )
    {
        $y_offset = 0;
        $x_offset = ($image_width - $image_height) / 2;
        $s_size     = $image_width - ($x_offset * 2);
    }else{
        $x_offset = 0;
        $y_offset = ($image_height - $image_width) / 2;
        $s_size = $image_height - ($y_offset * 2);
    }
    $new_canvas = imagecreatetruecolor( $square_size, $square_size); //Create a new true color image
    //Copy and resize part of an image with resampling
    if(imagecopyresampled($new_canvas, $source, 0, 0, $x_offset, $y_offset, $square_size, $square_size, $s_size, $s_size)){
        save_image($new_canvas, $destination, $image_type, $quality);
    }
    return true;
}
References save_image().
normal_resize_image()
if(isset($_POST) &&isset($_SERVER['HTTP_X_REQUESTED_WITH']) &&strtolower($_SERVER['HTTP_X_REQUESTED_WITH'])=='xmlhttprequest') normal_resize_image ($source, $destination, $image_type, $max_size, $image_width, $image_height, $quality)
{
    if($image_width <= 0 || $image_height <= 0){return false;} //return false if nothing to resize
    //do not resize if image is smaller than max size
    if($image_width <= $max_size && $image_height <= $max_size){
        if(save_image($source, $destination, $image_type, $quality)){
            return true;
        }
    }
    //Construct a proportional size of new image
    $image_scale    = min($max_size/$image_width, $max_size/$image_height);
    $new_width      = ceil($image_scale * $image_width);
    $new_height     = ceil($image_scale * $image_height);
    $new_canvas     = imagecreatetruecolor( $new_width, $new_height ); //Create a new true color image
    //Copy and resize part of an image with resampling
    if(imagecopyresampled($new_canvas, $source, 0, 0, 0, 0, $new_width, $new_height, $image_width, $image_height)){
        save_image($new_canvas, $destination, $image_type, $quality); //save resized image
    }
    return true;
}
References save_image().
save_image()
save_image ($source, $destination, $image_type, $quality)
{
    switch(strtolower($image_type)){//determine mime type
        case 'image/png':
            imagepng($source, $destination); return true; //save png file
            break;
        case 'image/gif':
            imagegif($source, $destination); return true; //save gif file
            break;
        case 'image/jpeg': case 'image/pjpeg':
            imagejpeg($source, $destination, $quality); return true; //save jpeg file
            break;
        default: return false;
    }
                                                                                                                                    }
Referenced by crop_image_square(), and normal_resize_image().
Variable Documentation
$arryv
$arryv = explode("*", $_POST['txtidf'])
$destination_folder
$destination_folder = $rimgv
$jpeg_quality
$jpeg_quality = 90
$max_image_size
$max_image_size = $maxv
$maxv
$maxv = $arryv[2]
$minv
$minv = $arryv[1]
$rimgv
$rimgv = $arryv[4]
$thumb_prefix
$thumb_prefix = "ch_"
$thumb_square_size
$thumb_square_size = $minv
$usnmv
$usnmv = $arryv[5]
$usnnv
$usnnv = $arryv[3]
$vidv
$vidv = $arryv[0]